dist: trusty
language: rust

rust:
  - stable

before_install:
  - sudo apt-get update
  - sudo apt-get install -y software-properties-common
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) main universe restricted multiverse"
  - sudo apt-get update
  - sudo apt-get -y install libegl1-mesa-dev libgles2-mesa-dev libglu1-mesa libglu1-mesa-dev libasound2-dev libsdl2-dev
  - sudo ldconfig
